# Generated by Django 6.1 on 2026-08-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_department_description_department_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='shiftroster',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shiftroster',
            name='shift_date',
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(default='Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='shiftroster',
            name='break_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftroster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftroster',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftroster',
            name='shift_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='shiftroster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
