# Generated by Django 6.1 on 2026-09-09 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


def backfill_nullable_fields(apps, schema_editor):
    LeaveRequest = apps.get_model('core', 'LeaveRequest')
    ShiftRoster = apps.get_model('core', 'ShiftRoster')

    now = timezone.now()
    LeaveRequest.objects.filter(created_at__isnull=True).update(created_at=now)
    ShiftRoster.objects.filter(created_at__isnull=True).update(created_at=now)
    ShiftRoster.objects.filter(name__isnull=True).update(name='General Shift')
    ShiftRoster.objects.filter(shift_type__isnull=True).update(shift_type='General')


def reverse_backfill_nullable_fields(apps, schema_editor):
    LeaveRequest = apps.get_model('core', 'LeaveRequest')
    ShiftRoster = apps.get_model('core', 'ShiftRoster')

    LeaveRequest.objects.all().update(created_at=None)
    ShiftRoster.objects.all().update(created_at=None, name=None, shift_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_department_manager_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_nullable_fields,
            reverse_code=reverse_backfill_nullable_fields,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shiftroster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shiftroster',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shiftroster',
            name='shift_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='General Expense', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
