# Generated by Django 6.1 on 2026-09-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_employee_resigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftroster",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="shiftroster",
            name="work_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
