# Generated by Django 6.1 on 2026-09-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_claimstatus"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payrollitem",
            unique_together={("payroll_run", "employee")},
        ),
    ]
