# Generated by Django 6.1 on 2026-09-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_payrollitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="resigned_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
