# Generated by Django 6.1 on 2026-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_shiftroster_employee_shiftroster_work_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clock_out__isnull", True)),
                fields=("employee",),
                name="one_open_attendance_per_employee",
            ),
        ),
    ]
