# Generated by Django 6.1 on 2026-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_attendance_one_open_attendance_per_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="shiftroster",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shiftroster",
            name="shift_type",
            field=models.CharField(default="General", max_length=50),
        ),
    ]
