# Generated by Django 6.1 on 2026-09-11 16:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("leave_type", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("days_total", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "leave_type"),
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
