# Generated by Django 6.1 on 2026-09-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_leaveallocation_days_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overtimeslip",
            name="attendance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.attendance"
            ),
        ),
    ]
