# Generated by Django 6.1 on 2026-09-13 05:45

import core.views_docs
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_attendance_one_open_attendance_per_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('NBI', 'NBI Clearance'), ('BIR2316', 'BIR Form 2316'), ('PSA', 'PSA Birth Certificate'), ('contract', 'Signed Employment Contract')], max_length=20)),
                ('file', models.FileField(upload_to='onboarding-docs/%Y/%m/%d/', validators=[core.views_docs.validate_onboarding_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_documents', to='core.employee')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('repayment_terms', models.CharField(default='Next Payroll', max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='core.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
