# Generated by Django 6.1 on 2026-09-14

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_payrollitem_base_pay_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("status", models.CharField(choices=[("Pending", "Pending"), ("Investigating", "Investigating"), ("In Mediation", "In Mediation"), ("Resolved", "Resolved"), ("Rejected", "Rejected")], default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.employee")),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
