# Generated by Django 6.1 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_grievance"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseclaim",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
