# Generated by Django 6.1 on 2026-09-15 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_expenseclaim_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints', to='core.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
