# Generated by Django 6.1 on 2026-09-15 06:28

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_complaint'),
    ]

    operations = [
        # The initial complaint table used a bigint id and has no rows yet.
        # Recreate it so PostgreSQL receives a native UUID primary key instead
        # of attempting an invalid bigint-to-uuid cast.
        migrations.DeleteModel(name='Complaint'),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('workplace', 'Workplace conduct'), ('harassment', 'Harassment'), ('payroll', 'Payroll issue'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Open', max_length=20)),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.employee')),
            ],
            options={'ordering': ('-created_at',)},
        ),
    ]
